# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VIMlurMeuYA_fxzo0dx1xGrD9SIfLJt1
"""

class Library:
    def __init__(self): # Corrected the initializer method name to __init__
        self.books = {}  # Dictionary to store book titles and their availability status

    def add_book(self, title):
        self.books[title] = True  # True means the book is available
        print(f"Book '{title}' added successfully.")

    def display_books(self):
        print("\nAvailable Books in Library:")
        available_books = [book for book, available in self.books.items() if available]
        if available_books:
            for book in available_books:
                print(f"- {book}")
        else:
            print("No books are available at the moment.")

    def issue_book(self, title):
        if title in self.books:
            if self.books[title]:  # Check if the book is available
                self.books[title] = False  # Set the book's availability to False
                print(f"Book '{title}' issued successfully.")
            else:
                print(f"Sorry, the book '{title}' is already issued.")
        else:
            print(f"Book '{title}' not found in the library.")

    def return_book(self, title):
        if title in self.books:
            if not self.books[title]:  # Check if the book is currently issued
                self.books[title] = True  # Set the book's availability to True
                print(f"Book '{title}' returned successfully.")
            else:
                print(f"The book '{title}' was not issued.")
        else:
            print(f"Book '{title}' not found in the library.")

def library_menu():
    library = Library()

    while True:
        print("\nLibrary Management System")
        print("1. Add Book")
        print("2. Display Books")
        print("3. Issue Book")
        print("4. Return Book")
        print("5. Exit")

        choice = input("Enter choice (1/2/3/4/5): ")

        if choice == '1':
            title = input("Enter book title to add: ")
            library.add_book(title)

        elif choice == '2':
            library.display_books()

        elif choice == '3':
            title = input("Enter book title to issue: ")
            library.issue_book(title)

        elif choice == '4':
            title = input("Enter book title to return: ")
            library.return_book(title)

        elif choice == '5':
            print("Exiting the Library Management System. Goodbye!")
            break

        else:
            print("Invalid choice! Please try again.")

# Run the Library Management System
library_menu()